
CREATE TABLE CARRIER(
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF varchar(11)

)

CREATE TABLE FUEL_CONSUMPTION (
    SERIAL_NUMBER  INTEGER PRIMARY KEY AUTO_INCREMENT,
    CARRIER_ID INTEGER REFERENCES CARRIER(ID),
    CAPACITY INTEGER,
)
